{{- if .Values.secrets.enabled }}
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: "{{ include "common.fullname" . }}-secrets"
spec: 
  keys:
    - secrets
  {{- if .Values.secrets.path }}
  path: {{ .Values.secrets.path}}
  {{- else }}
  path: "kv/{{ include "common.fullname" . }}"
  {{- end }}
  {{- if .Values.secrets.version}}
  version: {{ .Values.secrets.version}}
  {{- end }}
  type: Opaque
{{- end}}