---
apiVersion: v2
name: deployment-template # deployable unit
appVersion: "1.0"
description: "Deployment template"
version: 0.1.11
type: application
dependencies:
  - name: common
    version: 0.0.4
    repository: "file://../common"  # Adjust the path as needed
