# my-deployment/values.yaml

global:
  environment: Production
  name: this-is-the-default-name

secrets:
  enabled: false

replicaCount: 1
image:
  repository: docker-registry.mw/personal-website
  tag: 0.0.2
  pullPolicy: IfNotPresent

service:
  name: deployment
  type: ClusterIP
  port: 80
  targetPort: 80

ingress:
  enabled: true
  path: /
  host: .mw.local
  priority: 1
  tls: 
    enable: false

configMaps: []

appconfig: {}


extraManifests: []