
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common.fullname" . }}
  labels:
    app: {{ include "common.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: {{ include "common.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "common.fullname" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
          env:
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://otelcollector-service.monitoring.svc.cluster.local:4317"
            - name: ENVIRONMENT
              value: "{{ .Values.global.environment }}"
            - name: NAME
              value: "{{ include "common.fullname" . }}"
          volumeMounts:
            {{- if .Values.secrets.enable }}
            - name: appsecrets
              mountPath: /app/secrets.yaml
              subPath: secrets
            {{- end }}
            - name: appconfig
              mountPath: /app/appconfig.Production.yaml
              subPath: appconfig.Production.yaml
      volumes:
{{- if .Values.secrets.enable }}
        - name: appsecrets
          secret:
            secretName: "{{ include "common.fullname" . }}-secrets"
            defaultMode: 420
{{- end }}
        - name: appconfig
          configMap:
            name: "{{ include "common.fullname" . }}-appconfig" 
